BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }

    public int CuisineId { get; set; }
    public string Type { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;

namespace BestRestaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public CuisinesController(BestRestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      model.Sort((x, y) => string.Compare(x.Type, y.Type));
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(cuisine.Type))
        {
          throw new System.InvalidOperationException("invalid input");
        }
        else
        {
          _db.Cuisines.Add(cuisine);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch(Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      thisCuisine.Restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(cuisine.Type))
        {
          throw new System.InvalidOperationException("invalid input");
        }
        else
        {
          _db.Entry(cuisine).State = EntityState.Modified;
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch(Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      thisCuisine.Restaurants = _db.Restaurants.Where(restaurants => restaurants.CuisineId == id).ToList();
      foreach (Restaurant restaurant in thisCuisine.Restaurants)
      {
        _db.Restaurants.Remove(restaurant);
      }
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h1>ADD NEW CUISINE</h1>
@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.LabelFor(model => model.Type)
    @Html.TextBoxFor(model => model.Type)
  </div>
  
  <input type="submit" class="btn-block" value="ADD CUISINE" />
}

@Html.ActionLink("VIEW ALL CUISINES", "Index", "Cuisines", null, new { @class = "btn-block" })

BestRestaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h1>DELETE THIS CUISINE?</h1>
@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)
@using (Html.BeginForm())
{
  <input type="submit" class="btn-block" value="YES, DELETE" />
}

@Html.ActionLink("VIEW ALL CUISINES", "Index", "Cuisines", null, new { @class = "btn-block" })

BestRestaurants/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model BestRestaurants.Models.Cuisine;

<h1>CUISINE DETAILS</h1>
<hr />
<h4>@Html.DisplayNameFor(model => model.Type): @Html.DisplayFor(model => model.Type)</h4>

<ul>
@if (@Model.Restaurants.Count == 0)
{
  <p>no restaurants found</p>
}

@foreach (Restaurant restaurant in @Model.Restaurants)
{
  <li><a href="/Restaurants/Details/@restaurant.RestaurantId">@restaurant.Name</a></li>
}
</ul>

<div class="four-buttons">
  <a class="btn" href="/Restaurants/Create">ADD RESTAURANT</a>
  @Html.ActionLink("VIEW ALL CUISINES", "Index", "Cuisines", null, new { @class="btn" })
  @Html.ActionLink("EDIT CUISINE", "Edit", "Cuisines", new { id = Model.CuisineId }, new { @class="btn" })
  @Html.ActionLink("DELETE CUISINE", "Delete", "Cuisines", new { id = Model.CuisineId }, new { @class="btn" })
</div>

BestRestaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Cuisine

<h1>EDIT THIS CUISINE: @Html.DisplayFor(model => model.Type)</h1>
<hr />
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Type)
  @Html.EditorFor(model => model.Type)

  <input type="submit" class="btn-block" value="SAVE CHANGES" />
}

@Html.ActionLink("VIEW ALL CUISINES", "Index", "Cuisines", null, new { @class="btn-block" })

BestRestaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Cuisine>;

<h1>CUISINES</h1>

@if (@Model.Count == 0)
{
  <h4>no cuisines found</h4>
} 

@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Type}", "Details", new { id = cuisine.CuisineId })</li>
}

<div class="two-buttons">
  @Html.ActionLink("ADD NEW CUISINE", "Create", "Cuisines", null, new { @class="btn" })
  <a class="btn" href="/Restaurants/Create">ADD RESTAURANT</a>
</div>