BestRestaurants/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Restaurant
  {
    public Restaurant()
    {
      this.Reviews = new HashSet<Review>();
    }
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public int CuisineId { get; set; }
    public string PriceRange { get; set; }

    public virtual Cuisine Cuisine { get; set; }
    public virtual ICollection<Review> Reviews { get; set; }
  }
}

BestRestaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace BestRestaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public RestaurantsController(BestRestaurantsContext db)
    {
      _db = db;
    } 

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurants => restaurants.Cuisine).ToList();
      model.Sort((x, y) => string.Compare(x.Name, y.Name));
      return View(model);
    }

    public ActionResult Create()
    {
      try
      {
        List<Cuisine> cuisines = _db.Cuisines.ToList();
        if (cuisines.Count >= 1)
        {
          ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
          return View();
        }
        else
        {
          throw new System.InvalidOperationException("No cuisines available. Please add a cuisine before adding a restaurant.");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(restaurant.Name) || String.IsNullOrWhiteSpace(restaurant.PriceRange))
        {
          throw new System.InvalidOperationException("invalid input");
        }
        else
        {
          _db.Restaurants.Add(restaurant);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      thisRestaurant.Reviews = _db.Reviews.Where(review => review.RestaurantId == id).ToList();
      return View(thisRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Type");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(restaurant.Name) || String.IsNullOrWhiteSpace(restaurant.PriceRange))
        {
          throw new System.InvalidOperationException("invalid input");
        }
        else
        {
          _db.Entry(restaurant).State = EntityState.Modified;
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      thisRestaurant.Reviews = _db.Reviews.Where(reviews => reviews.RestaurantId == id).ToList();
      foreach(Review review in thisRestaurant.Reviews)
      {
        _db.Reviews.Remove(review);
      }
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace BestRestaurants.Controllers
{
  public class ReviewsController : Controller
  {
    private readonly BestRestaurantsContext _db;

    public ReviewsController(BestRestaurantsContext db)
    {
      _db = db;
    } 

    public ActionResult Index()
    {
      return View();
    }

    public ActionResult Create()
    {
      try
      {
        List<Restaurant> existingRestaurants = _db.Restaurants.ToList();
        if (existingRestaurants.Count >= 1)
        {
          ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
          return View();
        }
        else
        {
          throw new System.InvalidOperationException("No restaurants available to review.");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    [HttpPost]
    public ActionResult Create(Review review)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(review.Title) || String.IsNullOrWhiteSpace(review.Description))
        {
          throw new System.InvalidOperationException("invalid input");
        }
        else
        {
          _db.Reviews.Add(review);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch(Exception ex)
      {
        return View("Error", ex.Message);
      }
    }
  }
}

BestRestaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h1>ADD NEW RESTAURANT</h1>
@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.PriceRange)
    @Html.TextBoxFor(model => model.PriceRange)
  </div>
  <div class="form-group">
    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")
  </div>

  <input type="submit" value="ADD RESTAURANT" class="btn-block" />
}

@Html.ActionLink("VIEW ALL RESTAURANTS", "Index", "Restaurants", null, new { @class="btn-block" })

BestRestaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h1>DELETE THIS RESTAURANT?</h1>

<p class="delete">@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
@using (Html.BeginForm())
{
  <input type="submit" class="btn-block" value="YES, DELETE" />
}

@Html.ActionLink("VIEW ALL RESTAURANTS", "Index", "Restaurants", null, new { @class="btn-block" })

BestRestaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model BestRestaurants.Models.Restaurant

<h1>@Html.DisplayFor(model => model.Name)</h1>
<hr />
<h4>PRICE RANGE: @Html.DisplayFor(model => model.PriceRange)</h4>

@if (Model.Reviews.Count == 0)
{
  <h4>No reviews available</h4>
}
<hr />
<div id="reviews">
  <h3>REVIEWS</h3>
  @foreach (Review review in Model.Reviews)
  {
    <div id="review">
      <h4>@review.Title</h4>
      <hr />
      <p>@review.Description</p>
    </div>
  }
</div>

<div class="four-buttons">
  @Html.ActionLink("ADD REVIEW", "Create", "Reviews", null, new { @class="btn" })
  @Html.ActionLink("EDIT RESTAURANT", "Edit", "Restaurants", new { id = Model.RestaurantId }, new { @class="btn" })
  @Html.ActionLink("DELETE RESTAURANT", "Delete", "Restaurants", new { id = Model.RestaurantId }, new { @class="btn" })
  @Html.ActionLink("VIEW ALL RESTAURANTS", "Index", "Restaurants", null, new { @class="btn" })
</div>

BestRestaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurants.Models.Restaurant

<h1>EDIT DETAILS FOR @Html.DisplayFor(model => model.Name)</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.PriceRange)
  @Html.EditorFor(model => model.PriceRange)

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type="submit" class="btn-block" value="SAVE CHANGES" />
}

@Html.ActionLink("VIEW ALL RESTAURANTS", "Index", "Restaurants", null, new { @class="btn-block" })

BestRestaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>

<h1>RESTAURANTS</h1>

@if (@Model.Count == 0)
{
  <h4>no restaurants found</h4>
}

<ul>
  @foreach (Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId }) | @restaurant.Cuisine.Type</li>
  }
</ul>

@Html.ActionLink("ADD RESTAURANT", "Create", "Restaurants", null, new { @class="btn-block" })